before_script:
  - psql -c 'create database ff_test;' -U postgres
  - bundle exec rake db:migrate
language: ruby
rvm:
  - 1.9.3
notifications:
  webhooks:
    urls:
      - https://deployer.herokuapp.com/deploy?app=fastfeedback&key=iliketurtles
    on_success: always
    on_failure: never