development:
  adapter: postgresql
  encoding: unicode
  database: ff_development
  pool: 5
  username: postgres
  password:
  min_messages: WARNING 

  
test:
  adapter: postgresql
  encoding: unicode
  database: ff_test
  pool: 5
  username: postgres
  password:
  min_messages: WARNING 

production:
  adapter: postgresql
  encoding: unicode
  database: ff_production
  pool: 5
  username: postgres
  password:
